FROM docker.m.daocloud.io/library/node:20.11-alpine AS frontend-builder

WORKDIR /app

RUN sed -i 's|https://dl-cdn.alpinelinux.org/alpine|https://mirrors.tuna.tsinghua.edu.cn/alpine|g' /etc/apk/repositories \
    && npm config set registry https://registry.npmmirror.com

COPY frontend/package*.json ./frontend/
RUN cd frontend && npm ci

COPY frontend ./frontend
RUN cd frontend && npm run build

FROM docker.m.daocloud.io/library/nginx:1.26-alpine

COPY deploy/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=frontend-builder /app/frontend/dist /usr/share/nginx/html

RUN mkdir -p /usr/share/nginx/html/download

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
