export { default as Account } from './Account'
export { default as Admin } from './Admin'
export { default as Download } from './Download'
export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as Register } from './Register'
